
# Based on https://tobiasmcnulty.com/posts/caching-pre-commit/

name: "pre-commit"

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
      name: Checkout

    - uses: actions/setup-python@v4.8.0
      name: Install pre-commit
      with:
        python-version: "3.12"
        cache: "pip"
    - run: python -m pip install pre-commit
    - run: python -m pip freeze --local

    - uses: actions/cache@v3.0.0
      name: Run pre-commit checks
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: pre-commit run --show-diff-on-failure --color=always --all-files
